from modules.config import *

FUNSTAT_TOKEN = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_RqiTfJSjvlO_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
API_CONFIG = {
    1: {
        'name': 'BigBase',
        'label': 'API 1',
        'url': 'https://bigbase.top/api/search',
        'method': 'POST',
        'post_format': 'json',
        'payload': {'search': None, 'page': 0},
        'headers': {'Authorization': 'yhIkVgFWlT4ldeiauETMCFGkla7-VYtH'},
        'working': True,
        'is_phone_search': True,
        'is_email_search': True,
        'eta_weight': 1.0,
        'note': 'Основной агрегатор баз данных.',
    },
    2: {
        'name': 'Byrevesnik',
        'label': 'API 2',
        'url': 'http://atlas-in.cc/byrevesnik',
        'method': 'POST',
        'post_format': 'json',
        'payload': {'token': '1:3ZD4M416ND', 'type': 'phone', 'search': None},
        'headers': {},
        'working': False,
        'is_phone_search': True,
        'eta_weight': 5.0,
        'note': 'Выключено.',
    },
    3: {
        'name': 'Atlas Ares',
        'label': 'API 3',
        'url': 'https://atlas-in.cc/ares',
        'method': 'POST',
        'post_format': 'json',
        'payload': {'token': '7602672981:BYXI0WPATY', 'type': 'phone', 'search': None},
        'headers': {},
        'working': False,
        'is_phone_search': True,
        'eta_weight': 5.0,
        'note': 'Выключено.',
    },
    4: {
        'name': 'Atlas Mothership',
        'label': 'API 4',
        'url': 'https://atlas-in.cc/mothership',
        'method': 'POST',
        'post_format': 'json',
        'payload': {'token': '7602672981:CKJ7OEEZ8D', 'type': 'phone', 'search': None},
        'headers': {},
        'working': False,
        'is_phone_search': True,
        'eta_weight': 5.0,
        'note': 'Выключено.',
    },
    5: {
        'name': 'Krampus',
        'label': 'API 5',
        'url': 'http://krampus-ink.icu/api/v1',
        'method': 'GET',
        'payload': {
            'key': 'KRMP-QK6N-VBGH-HAXJ',
            'search': None,
            'type': 'phone',
            'method': 'full',
        },
        'headers': {},
        'working': False,
        'is_phone_search': True,
        'eta_weight': 9.5,
        'note': 'Выключено',
    },
    6: {
        'name': 'Atlas',
        'label': 'API 6',
        'url': 'https://atlas-in.cc/app',
        'method': 'POST',
        'post_format': 'json',
        'payload': {
            'api_key': '8139033962:QNMS85ELCZ',
            'query': None,
            'type': 'phone'
        },
        'headers': {'Content-Type': 'application/json'},
        'working': False,
        'is_phone_search': True,
        'eta_weight': 5.0,
        'note': 'Выключено.',
    },
    7: {
        'name': 'Cryven',
        'label': 'API 7',
        'url': 'https://cryven.biz/api/v1/search',
        'method': 'POST',
        'post_format': 'json',
        'payload': {'phone': None, 'time': 'fast'},
        'headers': {
            'Authorization': 'Bearer jIqixbIwixiOqxgIaOqhxtBqoOs',
            'Content-Type': 'application/json'
        },
        'working': False,
        'is_phone_search': True,
        'eta_weight': 0.6,
        'note': 'Выключено.',
    },
    8: {
        'name': 'Linkor',
        'label': 'API 8',
        'url': 'http://185.43.4.214:8084/api/v1/search',
        'method': 'GET',
        'payload': {'q': None, 'type': 'phone'},
        'headers': {
            'X-API-Key': 'lnk_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
        },
        'working': False,
        'is_phone_search': True,
        'eta_weight': 5.0,
        'note': 'Выключено.',
    },
    9: {
        'name': 'PulseSearch',
        'label': 'API 9',
        'url': 'https://pulsesearch.ru/api/v1/search',
        'method': 'POST',
        'post_format': 'form',
        'payload': {'query': None},
        'headers': {
            'X-API-Key': 'vsk_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
            'Content-Type': 'application/x-www-form-urlencoded'
        },
        'working': False,
        'is_phone_search': True,
        'eta_weight': 0.5,
        'note': 'Выключено.',
    },
    10: {
        'name': 'EpicAPI',
        'label': 'API 10',
        'url': 'https://epic-api.pro/api/v1/search/',
        'method': 'POST',
        'post_format': 'json',
        'payload': {'field': 'phone', 'value': None},
        'headers': {
            'Authorization': 'Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
            'Content-Type': 'application/json'
        },
        'working': False,
        'is_phone_search': True,
        'is_email_search': True,
        'is_fio_search': True,
        'is_ip_search': True,
        'is_username_search': True,
        'is_vin_search': True,
        'eta_weight': 0.3,
        'note': 'Выключено',
    },
    11: {
        'name': 'OfData',
        'label': 'API 11',
        'url': 'https://api.ofdata.ru/v2/search',
        'method': 'GET',
        'payload': {'key': 'KBnpz1CHKNngFXxK', 'by': 'name', 'obj': 'org', 'query': None},
        'headers': {},
        'working': True,
        'is_org_search': True,
        'note': 'Поиск по организациям и ИП.',
    },
    12: {
        'name': 'MikuSearch',
        'label': 'API 12',
        'url': 'https://mikusearchapi.loca.lt/search',
        'method': 'GET',
        'payload': {'key': '!MIM!J8T3M7S4!Z', 'search': None},
        'headers': {},
        'working': False,
        'is_phone_search': True,
        'is_email_search': True,
        'is_fio_search': True,
        'is_inn_search': True,
        'eta_weight': 2.0,
        'note': 'Выключено',
    },
    13: {
        'name': 'LeaxIX',
        'label': 'API 13',
        'url': 'https://leakix.net/host/{query}',
        'method': 'GET',
        'headers': {
            'api-key': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
            'Accept': 'application/json'
        },
        'working': True,
        'is_ip_search': True,
        'note': 'Поиск утечек и сервисов по IP.',
    },
    14: {
        'name': 'HTMLWeb',
        'label': 'API 14',
        'url': 'https://htmlweb.ru/geo/api.php',
        'method': 'GET',
        'payload': {'json': '', 'ip': None},
        'headers': {},
        'working': True,
        'is_ip_search': True,
        'note': 'Гео-данные по IP.',
    },
    15: {
        'name': 'HtmlWEB',
        'label': 'API 15',
        'url': 'https://htmlweb.ru/geo/api.php',
        'method': 'GET',
        'payload': {'json': '', 'telcod': None},
        'headers': {},
        'working': True,
        'is_phone_search': True,
        'note': 'Инфо по коду номера.',
    },
    16: {
        'name': 'EmailRep',
        'label': 'API 16',
        'url': 'https://emailrep.io/{query}',
        'method': 'GET',
        'headers': {},
        'working': True,
        'is_email_search': True,
        'note': 'Репутация email.',
    },
    17: {
        'name': 'XposedOrNot',
        'label': 'API 17',
        'url': 'https://api.xposedornot.com/v1/check-email/{query}',
        'method': 'GET',
        'headers': {},
        'working': True,
        'is_email_search': True,
        'note': 'Поиск в утечках.',
    },
    18: {
        'name': 'Rapid',
        'label': 'API 18',
        'url': 'https://rapid-email-verifier.fly.dev/api/validate',
        'method': 'GET',
        'payload': {'email': None},
        'headers': {},
        'working': True,
        'is_email_search': True,
        'note': 'Валидация адреса.',
    },
    19: {
        'name': 'API 19',
        'label': 'API 19',
        'url': 'http://phone-number-api.com/json/',
        'method': 'GET',
        'payload': {
            'number': None, 
            'fields': 'status,message,numberType,numberValid,formatE164,countryName,carrier,regionName,city,timezone'
        },
        'headers': {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept': 'application/json'
        },
        'working': False,
        'is_phone_search': True,
        'note': 'Выключено',
    },
    20: {
        'name': 'LeakCheck',
        'label': 'API 20',
        'url': 'https://leakcheck.io/api/v2/query/{query}?type=phone',
        'method': 'GET',
        'headers': {
            'X-API-Key': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
        },
        'working': False,
        'is_phone_search': True,
        'is_email_search': True,
        'note': 'Выключено',
    },
    21: {
        'name': 'NumVerify',
        'label': 'API 21',
        'url': 'http://apilayer.net/api/validate',
        'method': 'GET',
        'payload': {'access_key': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'number': None, 'format': 1},
        'headers': {},
        'working': False,
        'is_phone_search': True,
        'note': 'Выключено',
    },
    22: {
        'name': 'IpGeo',
        'label': 'API 22',
        'url': 'https://api.ipgeolocation.io/ipgeo',
        'method': 'GET',
        'payload': {'apiKey': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'ip': None},
        'headers': {},
        'working': True,
        'is_ip_search': True,
        'note': 'Геолокация червыфвыыффффio.',
    },
    23: {
        'name': 'skskskakann',
        'label': 'API 23',
        'url': 'https://api.depsearch.com/v1/search',
        'method': 'POST',
        'payload': {'token': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'search': None},
        'headers': {},
        'working': False,
        'is_phone_search': True,
        'is_email_search': True,
        'note': 'Выключено',
    },
    24: {
        'name': 'LeakOsint',
        'label': 'API 24',
        'url': 'https://leakosintapi.com/',
        'method': 'POST',
        'post_format': 'json',
        'payload': {
            'token': '8602726148:KHqZhmJC',
            'request': None,
            'limit': 100,
            'lang': 'ru'
        },
        'headers': {},
        'working': False,
        'is_phone_search': True,
        'is_email_search': True,
        'is_fio_search': True,
        'is_username_search': True,
        'is_vin_search': True,
        'note': 'Выключено.',
    },
    25: {
        'name': 'CheckHost',
        'label': 'API 25',
        'url': 'https://check-host.net/check-ping',
        'result_url': 'https://check-host.net/check-result',
        'method': 'GET',
        'payload': {'host': None, 'max_nodes': 3},
        'headers': {'Accept': 'application/json'},
        'working': True,
        'is_ip_search': True,
        'note': 'Проверка доступности IP с разных узлов.',
    },
    26: {
        'name': 'RDAP',
        'label': 'API 26',
        'url': 'https://rdap.arin.net/registry/ip/{query}',
        'method': 'GET',
        'headers': {'Accept': 'application/json'},
        'working': True,
        'is_ip_search': True,
        'note': 'WHOIS данные через RDAP.',
    },
    27: {
        'name': 'IPQualityScore',
        'label': 'API 27',
        'url': 'https://ipqualityscore.com/api/json/ip/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/{ip}',
        'method': 'GET',
        'payload': {},
        'headers': {},
        'working': True,
        'is_ip_search': True,
        'note': 'Выключено',
    },
    28: {
        'name': 'AbuseIPDB',
        'label': 'API 28',
        'url': 'https://api.abuseipdb.com/api/v2/check',
        'method': 'GET',
        'payload': {'ipAddress': None, 'maxAgeInDays': 90},
        'headers': {'Key': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Accept': 'application/json'},
        'working': False,
        'is_ip_search': True,
        'note': 'Выключено',
    },
    29: {
        'name': 'InfinitySearch',
        'label': 'API 29',
        'url': 'https://infinity-search.fun/find.php',
        'method': 'GET',
        'payload': {'token': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'phone': None},
        'headers': {},
        'working': True,
        'is_phone_search': True,
        'is_email_search': True,
        'is_fio_search': True,
        'eta_weight': 3.0,
        'note': 'Infinity Search — работает.',
    },
    30: {
        'name': 'TraceSearch',
        'label': 'API 30',
        'url': 'https://api.tracesearch.co/v1/search',
        'method': 'GET',
        'payload': {'type': None, 'quest': None, 'lang': 'ru'},
        'headers': {'Authorization': 'Bearer ts_16_bB0JLGup6gFs'},
        'working': False,
        'is_phone_search': True,
        'is_inn_search': True,
        'is_fio_search': True,
        'is_email_search': True,
        'is_vin_search': True,
        'is_username_search': True,
        'eta_weight': 1.0,
        'note': 'ему попа чучуть',
    },
    31: {
        'name': 'DepSearch',
        'label': 'API 31',
        'url': 'https://api.depsearch.sbs/quest={query}&token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'method': 'GET',
        'payload': {},
        'headers': {},
        'working': True,
        'is_phone_search': True,
        'is_email_search': True,
        'is_fio_search': True,
        'is_inn_search': True,
        'is_username_search': True,
        'is_vin_search': True,
        'eta_weight': 2.5,
        'note': ' — работает.',
    },
    32: {
        'name': 'LeakCheckPublic',
        'label': 'API 32',
        'url': 'https://leakcheck.net/api/public',
        'method': 'GET',
        'payload': {'key': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'check': None},
        'headers': {},
        'working': True,
        'is_email_search': True,
        'is_phone_search': True,
        'eta_weight': 1.5,
        'note': 'LeakCheck Public — поиск в утечках по email/телефону.',
    },
    33: {
        'name': 'Snusbase',
        'label': 'API 33',
        'url': 'https://api.snusbase.com/v3/search',
        'method': 'POST',
        'post_format': 'json',
        'payload': {'type': None, 'term': None},
        'headers': {
            'Auth': 'sb5029dec66mht55m78fx8bsw6tm8a',
            'Content-Type': 'application/json',
            'Accept': 'application/json',
            'User-Agent': 'Snusbase-Client/3.0'
        },
        'working': True,
        'is_email_search': True,
        'is_username_search': True,
        'is_ip_search': True,
        'is_fio_search': True,
        'eta_weight': 2.0,
        'note': 'Snusbase v3 — поиск по email, username, ip, name.',
    },
    34: {
        'name': 'GetScam',
        'label': 'API 34',
        'url': 'https://getscam.com/{query}',
        'method': 'GET',
        'headers': {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        },
        'working': True,
        'is_phone_search': True,
        'is_html_parser': True,
        'eta_weight': 3.0,
        'note': 'Парсинг getscam.com — информация о номере.',
    },
    35: {
        'name': 'ReviewsSite',
        'label': 'API 35',
        'url': 'https://xn---7-elctgilofd3b.xn--p1ai/{query}',
        'method': 'GET',
        'headers': {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        },
        'working': True,
        'is_phone_search': True,
        'is_html_parser': True,
        'eta_weight': 3.0,
        'note': 'Парсинг кто-звонил.рф — отзывы о номере.',
    },
    36: {
        'name': 'MySMSBox',
        'label': 'API 36',
        'url': 'https://mysmsbox.ru/phone-search/{query}',
        'method': 'GET',
        'headers': {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        },
        'working': True,
        'is_phone_search': True,
        'is_html_parser': True,
        'eta_weight': 3.0,
        'note': 'Парсинг mysmsbox.ru — категории и комментарии.',
    },
    37: {
        'name': 'WhatsApp',
        'label': 'API 37',
        'url': 'https://umnico.com/api/tools/checker',
        'method': 'GET',
        'payload': {'phone': None},
        'headers': {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        },
        'working': True,
        'is_phone_search': True,
        'eta_weight': 2.0,
        'note': 'Проверка регистрации в WhatsApp.',
    },
    38: {
        'name': 'DeepScan',
        'label': 'API 38',
        'url': 'https://deepscan.cc/api/v1/search',
        'method': 'POST',
        'post_format': 'json',
        'payload': {'token': 'deepscan_6747528307:bhOQD1ot', 'search': None},
        'headers': {'Content-Type': 'application/json'},
        'working': True,
        'is_phone_search': True,
        'is_fio_search': True,
        'is_email_search': True,
        'is_username_search': True,
        'is_ip_search': True,
        'is_vin_search': True,
        'is_inn_search': True,
        'eta_weight': 1.5,
        'note': '',
    },
    39: {
        'name': 'BlackEye',
        'label': 'API 39',
        'url': 'https://blackeyebot.duckdns.org/api/v1/search',
        'method': 'POST',
        'post_format': 'json',
        'payload': {'type': 'phone', 'q': None, 'limit': 100},
        'headers': {
            'Authorization': 'Bearer jn87axW1a3MSh8x83AJtDg',
            'Content-Type': 'application/json'
        },
        'working': True,
        'is_phone_search': True,
        'is_email_search': True,
        'is_fio_search': True,
        'is_ip_search': True,
        'is_username_search': True,
        'is_vin_search': True,
        'is_inn_search': True,
        'eta_weight': 3.0,
        'note': '',
    },
    40: {
        'name': 'Jitler',
        'label': 'API 40',
        'url': 'https://api.jitler.top/search',
        'result_url': 'https://api.jitler.top/search/{id}',
        'method': 'POST',
        'post_format': 'json',
        'payload': {'type': None, 'query': None, 'page': 1},
        'headers': {
            'Authorization': 'Bearer 7M8wfVQlszWnbaaINN2ig7iA',
            'Content-Type': 'application/json'
        },
        'working': True,
        'is_phone_search': True,
        'is_username_search': True,
        'is_vk_search': True,
        'is_async': True,
        'eta_weight': 1.5,
        'note': 'Jitler — поиск по номеру, шерлоку и ВК.',
    },
    41: {
        'name': 'Core',
        'label': 'API 41',
        'url': 'http://2.26.230.220:8081/search',
        'method': 'POST',
        'post_format': 'json',
        'payload': {'type': None, 'query': None},
        'headers': {
            'X-API-Key': '17aq_xu81(sbaop',
            'Content-Type': 'application/json'
        },
        'working': True,
        'is_phone_search': True,
        'is_email_search': True,
        'is_fio_search': True,
        'is_snils_search': True,
        'hide_source': True,
        'eta_weight': 1.5,
        'note': 'Core API.',
    },
    42: {
        'name': 'WhiteSearch',
        'label': 'API 42',
        'url': 'https://api.whitesearch.workers.dev/api',
        'method': 'GET',
        'headers': {'X-API-Key': 'WS-PUBLIC-9X7K-2M4P'},
        'working': True,
        'is_phone_search': True,
        'is_email_search': True,
        'is_fio_search': True,
        'is_ip_search': True,
        'is_vk_search': True,
        'is_snils_search': True,
        'is_inn_search': True,
        'is_vin_search': True,
        'is_username_search': True,
        'eta_weight': 1.5,
        'note': 'шота хуйня',
    },
    43: {
        'name': 'Nyx',
        'label': 'API 43',
        'url': 'https://api.w2sp3r.biz/nyx',
        'method': 'POST',
        'post_format': 'json',
        'payload': {'query': None},
        'headers': {
            'Authorization': 'Bearer Mg05qwg9kfJZgMA1sUshI_-LxS6c33iQWR4JslZRubc',
            'Content-Type': 'application/json'
        },
        'working': True,
        'is_phone_search': True,
        'is_email_search': True,
        'is_fio_search': True,
        'is_ip_search': True,
        'is_username_search': True,
        'is_vin_search': True,
        'is_snils_search': True,
        'eta_weight': 2.0,
        'note': 'Выключен.',
    },
}
